### PR TITLE
Fixed #1245 and Modified Dashboard and Quick Stats

### LINKED ISSUE #1245: menu permissions warning
warning: AbanteCart core v.1.2.15 Invalid argument supplied for foreach() in <b>/htdocs/admin/controller/common/menu.php</b> on line <b>47</b>
related to latest merge with pull  https://github.com/abantecart/abantecart-src/pull/1241

### PR DESCRIPTION
**Pull request by Ice-Drake**
Fixed menu permissions warning #1245

### CODE REVIEW

**Comment by Ice-Drake** [comment]
Modified Dashboard to change based on user group permissions.

**Comment by Ice-Drake** [comment]
Modified Quick Stats to change based on user group permissions.

**Comment by Ice-Drake** [comment]
Well, I am done with permission-admin-panel for now. Is there any plan to add more tables or modify certain tables in Dashboard page? How about any plan to modify Order page?

I want to split the Order page into a new page called Invoice. The Order page will have the column Total removed and Print Invoice will be changed to Print Shipping Label without any cost on it. The Invoice page will look like the original Order page without the option to change the Status.

Since making these changes is quite drastic, I don't think it is possible to make an extension for it would work. Thus, I am hoping if you guys might have a similar plan. I am looking forward in implementing such a feature.

**Comment by BasaraABC** [comment]
> I want to split the Order page into a new page called Invoice. 
> Since making these changes is quite drastic, I don't think it is possible to make an extension for it would work. 

I am sure this can be implement with extension system. Not a quick task but possible

**Comment by BasaraABC** [comment]
Thank you for your contribution.

**Pull request merged**
